# importing turtle
from turtle import *
import turtle
turtle.Screen()
t = turtle.Turtle()
t.shape("arrow")
t.color("black")
t.speed(100)

# left side of planet
begin_fill()
color("grey")
circle(150, 180)
end_fill()

# right side of planet
begin_fill()
color("DarkGreen")
circle(150, 180)
end_fill()
hideturtle()
# moving turtle to
t.up()
t.goto(-20, 300)
t.down()
t.left(90)
def domek(x = "gray", y = "black"):
    t.color(x)
    t.forward(30)
    t.left(90)
    t.forward(10)
    t.left(-135)
    t.forward(45)
    t.color(y)
    t.right(90)
    t.forward(45)
    t.right(135)
    t.forward(10)
    t.right(-90)
    t.forward(30)
domek()
t.up()
t.goto(20, 0)
t.down()
domek(x = "black", y = "gray")
t.hideturtle()
up()
goto(-550, 150)
showturtle()
begin_fill()
color("DarkGoldenrod2")
down()
circle(55)
end_fill()
hideturtle()
done()